// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Answer(Props) {
  var text = Props.text;
  var isShown = Props.isShown;
  var dispatch = Props.dispatch;
  if (isShown) {
    return React.createElement("div", undefined, text, React.createElement("div", undefined, React.createElement("button", {
                        onClick: (function (_event) {
                            return Curry._1(dispatch, /* Easy */0);
                          })
                      }, "Easy"), React.createElement("button", {
                        onClick: (function (_event) {
                            return Curry._1(dispatch, /* Medium */1);
                          })
                      }, "Medium"), React.createElement("button", {
                        onClick: (function (_event) {
                            return Curry._1(dispatch, /* Hard */2);
                          })
                      }, "Hard")));
  } else {
    return "";
  }
}

var make = Answer;

exports.make = make;
/* react Not a pure module */
