// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Card$ReactHooksTemplate = require("./Card.bs.js");

function reducer(state, action) {
  return /* record */[/* currentIndex */state[/* currentIndex */0] + 1 | 0];
}

var initialState = /* record */[/* currentIndex */0];

function Cards(Props) {
  var cards = Props.cards;
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  var toCard = function (card) {
    return React.createElement(Card$ReactHooksTemplate.make, {
                question: card[/* question */0],
                answer: card[/* answer */1],
                setDifficulty: (function (difficulty) {
                    return Curry._1(dispatch, /* SetDifficulty */[difficulty]);
                  })
              });
  };
  var cardsElements = toCard(List.nth(cards, match[0][/* currentIndex */0]));
  return React.createElement("div", undefined, cardsElements);
}

var make = Cards;

exports.reducer = reducer;
exports.initialState = initialState;
exports.make = make;
/* react Not a pure module */
