// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Answer$ReactHooksTemplate = require("./Answer.bs.js");

var initialState = /* record */[
  /* showAnswer */false,
  /* lastDifficulty : None */3
];

function reducer(state, action) {
  if (action) {
    return /* record */[
            /* showAnswer */state[/* showAnswer */0],
            /* lastDifficulty */action[0]
          ];
  } else {
    return /* record */[
            /* showAnswer */true,
            /* lastDifficulty */state[/* lastDifficulty */1]
          ];
  }
}

function Card(Props) {
  var question = Props.question;
  var answer = Props.answer;
  var setDifficulty = Props.setDifficulty;
  var match = React.useReducer(reducer, initialState);
  var dispatch = match[1];
  console.log("re-render");
  return React.createElement("div", undefined, question, React.createElement("button", {
                  onClick: (function (_event) {
                      return Curry._1(dispatch, /* Show */0);
                    })
                }, "Show Answer"), React.createElement(Answer$ReactHooksTemplate.make, {
                  text: answer,
                  isShown: match[0][/* showAnswer */0],
                  dispatch: setDifficulty
                }));
}

var make = Card;

exports.initialState = initialState;
exports.reducer = reducer;
exports.make = make;
/* react Not a pure module */
