// Generated by BUCKLESCRIPT VERSION 5.0.3, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var Cards$ReactHooksTemplate = require("./Cards.bs.js");

ReactDOMRe.renderToElementWithId(React.createElement(Cards$ReactHooksTemplate.make, {
          cards: /* :: */[
            /* record */[
              /* question */"1",
              /* answer */"answer1"
            ],
            /* :: */[
              /* record */[
                /* question */"2",
                /* answer */"answer2"
              ],
              /* [] */0
            ]
          ]
        }), "card");

/*  Not a pure module */
